[project]
name = "nyc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deltalake>=1.1.4",
    "docker>=7.1.0",
    "dotenv>=0.9.9",
    "duckdb>=1.4.0",
    "mkdocs>=1.6.1",
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "psycopg2>=2.9.10",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.43",
]
