[project]
name = "etl-batch"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "mkdocs>=1.6.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "semgrep>=1.86.0",
    "structlog>=25.4.0",
    "typing>=3.10.0.0",
]
